### ISSUE TITLE
undefined method `start_with?' for nil:NilClass

### ISSUE THREAD

**Issue by henriquesobral** [doabit/semantic-ui-sass#79]
Hi,

after I updated semantic-ui-sass to 2.2.1.0 version, I'm getting this error:
``undefined method `start_with?' for nil:NilClass``

After some tests, I found where the problem is:
``app/assets/stylesheets/semantic-ui/elements/_flags.scss - Line: 34``

I changed the image-url path of flags.png by removing './' at the start of string. I don't know if the flags will work with the change I've made, because I'm not using them.
